services:
  - type: web
    name: ai-manifest-engine
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node web-dashboard/server.js
    envVars:
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: CLAUDE_API_KEY
        sync: false
      - key: SESSION_SECRET
        sync: false
